site_name: FK743M5 Demo
site_author: Katbert
site_description: Just a FK743M5 demo project
repo_url: https://github.com/katbert-92/fk743m5
site_dir: 'docs_mkdoc/'
docs_dir: 'docs/'
strict: true

plugins:
  - search
  - mermaid2
  - callouts
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  