#ifndef __RTOS_ANALYZER_CFG
#define __RTOS_ANALYZER_CFG

#define RTOS_ANALYZER_MIN_TASK_STACK_SIZE_TRIG (50 * sizeof(u32))
#define RTOS_ANALYZER_MIN_HEAP_SIZE_TRIG	   (DATA_1_KBYTE * 10)
#define RTOS_ANALYZER_STARTUP_DELAY			   (DELAY_1_MINUTE * 2)
#define RTOS_ANALYZER_WORK_DELAY			   (DELAY_1_MINUTE)
#define RTOS_ANALYZER_TASKS_MAX_NUM			   40
#define RTOS_ANALYZER_SHELL_BUFF_SIZE		   256

#endif /* __RTOS_ANALYZER_CFG */
